apiVersion: database.mydomain.com/v1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: my-operator
    app.kubernetes.io/managed-by: kustomize
  name: database-sample
spec:
  # TODO(user): Add fields here
